foundry = {
    "reasoning-auseast": [
        "gpt-4o-reasoning-8",
        "gpt-4o-reasoning-4",
        "gpt-4o-reasoning-5",
    ],
    "reasoning-brsouth": [
        "gpt-4o-reasoning-9",
        "gpt-4o-reasoning-80",
        "gpt-4o-reasoning-81",
    ],
    "reasoning": [
        "gpt-4o-reasoning-26",
        "gpt-4o-reasoning-35",
        "gpt-4o-reasoning-86",
    ],
    "reasoning-westeu": [
        "gpt-4o-reasoning-14",
        "gpt-4o-reasoning-23",
        "gpt-4o-reasoning-44",
        "gpt-4o-reasoning-54",
        "gpt-4o-reasoning-55",
    ],
    "reasoning-stcent": [
        "gpt-4o-reasoning-1",
        "gpt-4o-reasoning-30",
        "gpt-4o-reasoning-39",
        "gpt-4o-reasoning-42",
        "gpt-4o-reasoning-43",
        "gpt-4o-reasoning-85",
    ],
    "reasoning-eastus": [
        "gpt-4o-reasoning-2",
        "gpt-4o-reasoning-27",
        "gpt-4o-reasoning-36",
        "gpt-4o-reasoning-51",
        "gpt-4o-reasoning-52",
        "gpt-4o-reasoning-82",
    ],
    "reasoning-eastus2": [
        "gpt-4o-reasoning-3",
        "gpt-4o-reasoning-28",
        "gpt-4o-reasoning-37",
        "gpt-4o-reasoning-6",
        "gpt-4o-reasoning-7",
        "gpt-4o-reasoning-46",
    ],
    "reasoning-japeast": [
        "gpt-4o-reasoning-11",
        "gpt-4o-reasoning-76",
        "gpt-4o-reasoning-77",
    ],
    "reasoning-uksouth": [
        "gpt-4o-reasoning-16",
        "gpt-4o-reasoning-56",
        "gpt-4o-reasoning-57",
    ],
    "reasoning-kocent": [
        "gpt-4o-reasoning-15",
        "gpt-4o-reasoning-69",
        "gpt-4o-reasoning-70",
    ],
    "reasoning-frcent": [
        "gpt-4o-reasoning-13",
        "gpt-4o-reasoning-34",
        "gpt-4o-reasoning-45",
        "gpt-4o-reasoning-65",
        "gpt-4o-reasoning-75",
    ],
    "reasoning-ntcent": [
        "gpt-4o-reasoning-31",
        "gpt-4o-reasoning-40",
        "gpt-4o-reasoning-83",
    ],
    "reasoning-souafnorth": [
        "gpt-4o-reasoning-20",
        "gpt-4o-reasoning-64",
        "gpt-4o-reasoning-68",
    ],
    "reasoning-uaenorth": [
        "gpt-4o-reasoning-17",
        "gpt-4o-reasoning-58",
        "gpt-4o-reasoning-59",
    ],
    "reasoning-swecent": [
        "gpt-4o-reasoning-29",
        "gpt-4o-reasoning-38",
        "gpt-4o-reasoning-84",
    ],
    "reasoning-switnorth": [
        "gpt-4o-reasoning-12",
        "gpt-4o-reasoning-73",
        "gpt-4o-reasoning-74",
    ],
    "reasoning-grwestcent": [
        "gpt-4o-reasoning-18",
        "gpt-4o-reasoning-33",
        "gpt-4o-reasoning-47",
        "gpt-4o-reasoning-71",
        "gpt-4o-reasoning-72",
    ],
    "reasoning-noreast": [
        "gpt-4o-reasoning-53",
        "gpt-4o-reasoning-87",
        "gpt-4o-reasoning-88",
    ],
    "reasoning-westus3": [
        "gpt-4o-reasoning-41",
        "gpt-4o-reasoning-50",
        "gpt-4o-reasoning-32",
    ],
    "reasoning-caneast": [
        "gpt-4o-reasoning-10",
        "gpt-4o-reasoning-78",
        "gpt-4o-reasoning-79",
    ],
    "reasoning-polcent": [
        "gpt-4o-reasoning-19",
        "gpt-4o-reasoning-24",
        "gpt-4o-reasoning-48",
        "gpt-4o-reasoning-66",
        "gpt-4o-reasoning-67",
    ],
    "reasoning-southindia": [
        "gpt-4o-reasoning-21",
        "gpt-4o-reasoning-62",
        "gpt-4o-reasoning-63",
    ],
    "reasoning-spcent": [
        "gpt-4o-reasoning-22",
        "gpt-4o-reasoning-25",
        "gpt-4o-reasoning-49",
        "gpt-4o-reasoning-60",
        "gpt-4o-reasoning-61",
    ],
}
